name: Auto Deploy Subdomain

on:
  push:
    paths:
      - 'subdomains/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Pages
        run: echo "Pretend to deploy subdomain"